spring.application.name=demo

server.port=${PORT:5000}

salesforce.clientId=${salesforce.clientId}
salesforce.clientSecret=${salesforce.clientSecret}
salesforce.redirectUri=${salesforce.redirectUri}

frontend.url=${frontend.url}
